# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "AmuroEita"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 60

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'
json_wechat_path: './docs/arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "MoE inference":
        filters: ["MoE inference", "MoE models", "MoE", "Accelerate"]
    "LLM inference":
        filters: ["LLM", "LLM inference", "GEMM" ,"GEMV","Large Language Model Inference","Accelerators","inference"]
    "chiplet":
        filters: ["chiplet", "LLM inference", "edge", "Wafer-Scale","3D", "Heterogeneous","2.5D"]
    "Parallel and Concurrent Algorithms":
        filters: ["Multithreading", "Task Scheduling", "Load Balancing", "Parallel Graph"]
    "CPU and Memory Cache":
        filters: ["Cache Coherence", "Memory Hierarchy", "Prefetching Techniques", "Branch Prediction", "Pipeline Optimization"]
